# Generated by Django 2.2 on 2019-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativo', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(editable=False)),
                ('usuario_api', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
            },
        ),
    ]
