version: 2.1
jobs:
  build:
    docker: 
      - image: fedora # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls
  deploy:
    machine:
      enabled: true
    steps:    
      - add_ssh_keys:
          fingerprints:
            - "5a:59:6e:f5:c0:a1:82:da:1e:61:2e:48:de:d3:4a:91"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "ls && exit"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy          